---
resources:
- name: source
  type: git
  source:
    uri: git@github.com:maluramichael/concourse-ci-test.git
    branch: master
    private_key: ((github_private_key))

jobs:
- name: build
  plan:
  - get: source
    trigger: true
  - task: dependencies
    file: source/.ci/tasks/dependencies.yml
  - task: build
    file: source/.ci/tasks/build.yml
  - task: deploy
    file: source/.ci/tasks/deploy.yml
